# Generated by Django 2.2.20 on 2021-08-05 14:29

from django.db import migrations
import phonenumbers


def create_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = f'{phone.country_code}{phone.national_number}'
        flat.save()


def backwards(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = f'{phone.country_code}{phone.national_number}'
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20210805_1659'),
    ]

    operations = [
        migrations.RunPython(create_owner_pure_phone, backwards)
    ]
