# Generated by Django 2.2.20 on 2021-08-05 16:51

from django.db import migrations


def copy_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210805_1901'),
    ]

    operations = [
        migrations.RunPython(copy_owner, move_backward)
    ]
