# Generated by Django 2.2.20 on 2021-08-05 16:51

from django.db import migrations


def copy_owner(apps, schema_editor):
    Owners = apps.get_model('property', 'Owner')
    Flats = apps.get_model('property', 'Flat')
    for flat in Flats.objects.all():
        Owners.objects.get_or_create(
            owner=flat.owner,
            defaults={
                'owners_phonenumber': flat.owners_phonenumber,
                'owner_pure_phone': flat.owner_pure_phone
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210805_1901'),
    ]

    operations = [
        migrations.RunPython(copy_owner)
    ]
